onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -radix unsigned /topleveltestbench/clk
add wave -noupdate -radix unsigned /topleveltestbench/A/ByteEnable
add wave -noupdate -radix unsigned /topleveltestbench/A/PC
add wave -noupdate -radix unsigned /topleveltestbench/A/rst
add wave -noupdate -label DATA -radix binary /topleveltestbench/A/gdfx_temp0
add wave -noupdate -label ADDR /topleveltestbench/A/SYNTHESIZED_WIRE_23
add wave -noupdate -label RD /topleveltestbench/A/SYNTHESIZED_WIRE_22
add wave -noupdate -label WR /topleveltestbench/A/SYNTHESIZED_WIRE_21
add wave -noupdate /topleveltestbench/A/b2v_inst/fault_signal
add wave -noupdate /topleveltestbench/A/b2v_inst/A
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUA
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUB
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUOP
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUOut
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUPC
add wave -noupdate /topleveltestbench/A/b2v_inst/ALUzero
add wave -noupdate /topleveltestbench/A/b2v_inst/AUIPC
add wave -noupdate /topleveltestbench/A/b2v_inst/B
add wave -noupdate /topleveltestbench/A/b2v_inst/ba
add wave -noupdate /topleveltestbench/A/b2v_inst/BRANCH
add wave -noupdate /topleveltestbench/A/b2v_inst/branch_immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/brcnd
add wave -noupdate /topleveltestbench/A/b2v_inst/brhalted
add wave -noupdate /topleveltestbench/A/b2v_inst/brimmext
add wave -noupdate /topleveltestbench/A/b2v_inst/brmem_align_exception
add wave -noupdate /topleveltestbench/A/b2v_inst/brmul
add wave -noupdate /topleveltestbench/A/b2v_inst/brpc_mem_align_exception
add wave -noupdate /topleveltestbench/A/b2v_inst/bruncnd
add wave -noupdate /topleveltestbench/A/b2v_inst/C
add wave -noupdate /topleveltestbench/A/b2v_inst/caseba
add wave -noupdate /topleveltestbench/A/b2v_inst/cc
add wave -noupdate /topleveltestbench/A/b2v_inst/clk
add wave -noupdate /topleveltestbench/A/b2v_inst/destination
add wave -noupdate /topleveltestbench/A/b2v_inst/function3
add wave -noupdate /topleveltestbench/A/b2v_inst/function7
add wave -noupdate /topleveltestbench/A/b2v_inst/halted
add wave -noupdate /topleveltestbench/A/b2v_inst/immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/immext
add wave -noupdate /topleveltestbench/A/b2v_inst/invalid_opcode
add wave -noupdate /topleveltestbench/A/b2v_inst/IR
add wave -noupdate /topleveltestbench/A/b2v_inst/JAL
add wave -noupdate /topleveltestbench/A/b2v_inst/jal_immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/jalimmext
add wave -noupdate /topleveltestbench/A/b2v_inst/JALR
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED0
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED5
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED6
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED7
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED8
add wave -noupdate /topleveltestbench/A/b2v_inst/LED_ALTERA_SYNTHESIZED9
add wave -noupdate /topleveltestbench/A/b2v_inst/LOAD
add wave -noupdate /topleveltestbench/A/b2v_inst/LUI
add wave -noupdate /topleveltestbench/A/b2v_inst/MDROutput
add wave -noupdate /topleveltestbench/A/b2v_inst/MEM
add wave -noupdate /topleveltestbench/A/b2v_inst/mem_align_exception
add wave -noupdate /topleveltestbench/A/b2v_inst/MemoryDataIn
add wave -noupdate /topleveltestbench/A/b2v_inst/mxA
add wave -noupdate /topleveltestbench/A/b2v_inst/mxALUOP
add wave -noupdate /topleveltestbench/A/b2v_inst/mxB
add wave -noupdate /topleveltestbench/A/b2v_inst/mxMEM
add wave -noupdate /topleveltestbench/A/b2v_inst/mxPC
add wave -noupdate /topleveltestbench/A/b2v_inst/mxReg
add wave -noupdate /topleveltestbench/A/b2v_inst/one
add wave -noupdate /topleveltestbench/A/b2v_inst/OP
add wave -noupdate /topleveltestbench/A/b2v_inst/OP_IMM
add wave -noupdate /topleveltestbench/A/b2v_inst/opcode
add wave -noupdate /topleveltestbench/A/b2v_inst/PC_ALTERA_SYNTHESIZED
add wave -noupdate /topleveltestbench/A/b2v_inst/pc_mem_align_exception
add wave -noupdate /topleveltestbench/A/b2v_inst/rst
add wave -noupdate /topleveltestbench/A/b2v_inst/shift_immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/source1
add wave -noupdate /topleveltestbench/A/b2v_inst/source2
add wave -noupdate /topleveltestbench/A/b2v_inst/state
add wave -noupdate /topleveltestbench/A/b2v_inst/STORE
add wave -noupdate /topleveltestbench/A/b2v_inst/store_immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/storeimmext
add wave -noupdate /topleveltestbench/A/b2v_inst/upimmext
add wave -noupdate /topleveltestbench/A/b2v_inst/upimmshifted
add wave -noupdate /topleveltestbench/A/b2v_inst/upper_immediate
add wave -noupdate /topleveltestbench/A/b2v_inst/wr_ALTERA_SYNTHESIZED
add wave -noupdate /topleveltestbench/A/b2v_inst/wr_ALTERA_SYNTHESIZED0
add wave -noupdate /topleveltestbench/A/b2v_inst/wrAB
add wave -noupdate /topleveltestbench/A/b2v_inst/wrbrPC
add wave -noupdate /topleveltestbench/A/b2v_inst/wrC
add wave -noupdate /topleveltestbench/A/b2v_inst/wrIR
add wave -noupdate /topleveltestbench/A/b2v_inst/wrMEM
add wave -noupdate /topleveltestbench/A/b2v_inst/wrPC
add wave -noupdate /topleveltestbench/A/b2v_inst/wrReg
add wave -noupdate /topleveltestbench/A/b2v_inst/zero
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_0
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_1
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_2
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_3
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_4
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_5
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_6
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_7
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_8
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_9
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_10
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_11
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_12
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_13
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_14
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_15
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_16
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_17
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_18
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_19
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_20
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_21
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_22
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_23
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_24
add wave -noupdate /topleveltestbench/A/b2v_inst/SYNTHESIZED_WIRE_25
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_7
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_10
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_11
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_5
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_4
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_9
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_8
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_3
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_6
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_1
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_2
add wave -noupdate /topleveltestbench/A/b2v_inst/GDFX_TEMP_SIGNAL_0
add wave -noupdate /topleveltestbench/A/b2v_inst3/acked
add wave -noupdate /topleveltestbench/A/b2v_inst3/ba
add wave -noupdate /topleveltestbench/A/b2v_inst3/bitsIsNot11
add wave -noupdate /topleveltestbench/A/b2v_inst3/branch
add wave -noupdate /topleveltestbench/A/b2v_inst3/brbitsIsNot11
add wave -noupdate /topleveltestbench/A/b2v_inst3/brtimerIsNot0
add wave -noupdate /topleveltestbench/A/b2v_inst3/bruncnd
add wave -noupdate /topleveltestbench/A/b2v_inst3/Buttons
add wave -noupdate /topleveltestbench/A/b2v_inst3/cc
add wave -noupdate /topleveltestbench/A/b2v_inst3/changed
add wave -noupdate /topleveltestbench/A/b2v_inst3/clBits
add wave -noupdate /topleveltestbench/A/b2v_inst3/clkFalling
add wave -noupdate /topleveltestbench/A/b2v_inst3/const0
add wave -noupdate /topleveltestbench/A/b2v_inst3/const350
add wave -noupdate /topleveltestbench/A/b2v_inst3/const599
add wave -noupdate /topleveltestbench/A/b2v_inst3/const799
add wave -noupdate /topleveltestbench/A/b2v_inst3/Counter
add wave -noupdate /topleveltestbench/A/b2v_inst3/dataIsFA
add wave -noupdate /topleveltestbench/A/b2v_inst3/dataValue
add wave -noupdate /topleveltestbench/A/b2v_inst3/decTimer
add wave -noupdate /topleveltestbench/A/b2v_inst3/DeltaX
add wave -noupdate /topleveltestbench/A/b2v_inst3/DeltaY
add wave -noupdate /topleveltestbench/A/b2v_inst3/FinalX
add wave -noupdate /topleveltestbench/A/b2v_inst3/FinalY
add wave -noupdate /topleveltestbench/A/b2v_inst3/memUpdated
add wave -noupdate /topleveltestbench/A/b2v_inst3/NewX
add wave -noupdate /topleveltestbench/A/b2v_inst3/NewY
add wave -noupdate /topleveltestbench/A/b2v_inst3/one
add wave -noupdate /topleveltestbench/A/b2v_inst3/OutY
add wave -noupdate /topleveltestbench/A/b2v_inst3/packetsFull
add wave -noupdate /topleveltestbench/A/b2v_inst3/pulldownCLK
add wave -noupdate /topleveltestbench/A/b2v_inst3/RData
add wave -noupdate /topleveltestbench/A/b2v_inst3/srDataAndIncBitsOnFallingEdge
add wave -noupdate /topleveltestbench/A/b2v_inst3/Status
add wave -noupdate /topleveltestbench/A/b2v_inst3/timerIsNot0
add wave -noupdate /topleveltestbench/A/b2v_inst3/wrData
add wave -noupdate /topleveltestbench/A/b2v_inst3/X
add wave -noupdate /topleveltestbench/A/b2v_inst3/XChanged
add wave -noupdate /topleveltestbench/A/b2v_inst3/XOverflow
add wave -noupdate /topleveltestbench/A/b2v_inst3/XUnderflow
add wave -noupdate /topleveltestbench/A/b2v_inst3/Y
add wave -noupdate /topleveltestbench/A/b2v_inst3/YChanged
add wave -noupdate /topleveltestbench/A/b2v_inst3/YOverflow
add wave -noupdate /topleveltestbench/A/b2v_inst3/YUnderflow
add wave -noupdate /topleveltestbench/A/b2v_inst3/zero
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_0
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_1
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_2
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_3
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_4
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_5
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_6
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_7
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_8
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_9
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_10
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_11
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_12
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_13
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_14
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_15
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_16
add wave -noupdate /topleveltestbench/A/b2v_inst3/SYNTHESIZED_WIRE_17
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_6
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_1
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_4
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_3
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_5
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_2
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_8
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_0
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_7
add wave -noupdate /topleveltestbench/A/b2v_inst3/GDFX_TEMP_SIGNAL_9
add wave -noupdate /topleveltestbench/A/b2v_inst1/BugB
add wave -noupdate /topleveltestbench/A/b2v_inst1/BugG
add wave -noupdate /topleveltestbench/A/b2v_inst1/BugR
add wave -noupdate /topleveltestbench/A/b2v_inst1/CNTRL
add wave -noupdate /topleveltestbench/A/b2v_inst1/COLOR
add wave -noupdate /topleveltestbench/A/b2v_inst1/cursor
add wave -noupdate /topleveltestbench/A/b2v_inst1/DATA1x
add wave -noupdate /topleveltestbench/A/b2v_inst1/DATA2x
add wave -noupdate /topleveltestbench/A/b2v_inst1/EN
add wave -noupdate /topleveltestbench/A/b2v_inst1/eX
add wave -noupdate /topleveltestbench/A/b2v_inst1/eY
add wave -noupdate /topleveltestbench/A/b2v_inst1/HIT
add wave -noupdate /topleveltestbench/A/b2v_inst1/ldCNTRL
add wave -noupdate /topleveltestbench/A/b2v_inst1/ldCOLOR
add wave -noupdate /topleveltestbench/A/b2v_inst1/ldDATA1x
add wave -noupdate /topleveltestbench/A/b2v_inst1/ldDATA2x
add wave -noupdate /topleveltestbench/A/b2v_inst1/LDFC
add wave -noupdate /topleveltestbench/A/b2v_inst1/ldSTATUS
add wave -noupdate /topleveltestbench/A/b2v_inst1/MSFC
add wave -noupdate /topleveltestbench/A/b2v_inst1/MSWR
add wave -noupdate /topleveltestbench/A/b2v_inst1/OP
add wave -noupdate /topleveltestbench/A/b2v_inst1/opCMPL
add wave -noupdate /topleveltestbench/A/b2v_inst1/opDrawLine
add wave -noupdate /topleveltestbench/A/b2v_inst1/opDrawPix
add wave -noupdate /topleveltestbench/A/b2v_inst1/opDrawRect
add wave -noupdate /topleveltestbench/A/b2v_inst1/opFillRect
add wave -noupdate /topleveltestbench/A/b2v_inst1/opGetPix
add wave -noupdate /topleveltestbench/A/b2v_inst1/outCOLOR
add wave -noupdate /topleveltestbench/A/b2v_inst1/Pixop
add wave -noupdate /topleveltestbench/A/b2v_inst1/RDFC
add wave -noupdate /topleveltestbench/A/b2v_inst1/ready
add wave -noupdate /topleveltestbench/A/b2v_inst1/Rectop
add wave -noupdate /topleveltestbench/A/b2v_inst1/run
add wave -noupdate /topleveltestbench/A/b2v_inst1/start
add wave -noupdate /topleveltestbench/A/b2v_inst1/STATUS
add wave -noupdate /topleveltestbench/A/b2v_inst1/sX
add wave -noupdate /topleveltestbench/A/b2v_inst1/sY
add wave -noupdate /topleveltestbench/A/b2v_inst1/wrCNTRL
add wave -noupdate /topleveltestbench/A/b2v_inst1/wrDATA1x
add wave -noupdate /topleveltestbench/A/b2v_inst1/wrDATA2x
add wave -noupdate /topleveltestbench/A/b2v_inst1/wrSTATUS
add wave -noupdate /topleveltestbench/A/b2v_inst1/ZERO
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_45
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_1
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_46
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_4
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_5
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_8
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_47
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_48
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_49
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_12
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_13
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_14
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_17
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_18
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_50
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_27
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_28
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_29
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_30
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_31
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_32
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_33
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_34
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_35
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_36
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_37
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_38
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_39
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_40
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_41
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_42
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_43
add wave -noupdate /topleveltestbench/A/b2v_inst1/SYNTHESIZED_WIRE_44
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_7
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_6
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_5
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_4
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_3
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_2
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_0
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_8
add wave -noupdate /topleveltestbench/A/b2v_inst1/GDFX_TEMP_SIGNAL_1
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {47901 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 311
configure wave -valuecolwidth 268
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 5000
configure wave -gridperiod 10000
configure wave -griddelta 40
configure wave -timeline 1
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1952464 ps}
